### ISSUE TITLE
Fatal error: Cannot declare class lib\Cake\Core\App because the name is already in use

### ISSUE THREAD

**Issue by alexmanrique** [cakephp/upgrade#83]
I have upgraded my old cakephp 2.x application to cakephp 3 using upgrade, and after deploying the application in htdocs of my XAMPP server I get the following error 

Fatal error: Cannot declare class lib\Cake\Core\App because the name is already in use in /Applications/XAMPP/xamppfiles/htdocs/ ... lib/Cake/Core/App.php on line 70

how can I fix this?

maybe when upgrading some folders have copied by error?

EDIT: when I try to run cake built-in server from bin/cake server it returns an error because it cannot find cake_core_libs 

thanks

**Comment by markstory** [comment]
Looks like you haven't removed the old cakephp libraries from your app source. You should try removing the lib directory.

**Comment by alexmanrique** [comment]
If I delete the lib directory from /Application_root_diretory/lib which is at the same level as /Application_root_diretory/app

after deploying the application in XAMPP server I get the following error: 

Warning: include(/Applications/XAMPP/xamppfiles/htdocs/***/lib/Cake/bootstrap.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/***/app/webroot/index.php on line 88

this error happens because app/webroot/index.php looks for CAKE_CORE_INCLUDE_PATH see the following code
```
if (!include(CAKE_CORE_INCLUDE_PATH . DS . 'Cake' . DS . 'bootstrap.php')) {
			$failed = true;
}
```
I have compared cakephp files from a cakephp 3.0 application build from scratch and there are differences because in app/webroot/index.php has the folllowing code lines:
```
require dirname(__DIR__) . '/config/bootstrap.php';
```
this leads me to think that upgrade tool is not setting files and directories properly as a cakephp 3 application build from scratch...

any idea? I should not have to do it manually ...

**Comment by markstory** [comment]
You have to replace the files in webroot with those from the new app skeleton. The upgrade shell may not have the most recent app skeleton changes. I can look into resolving that.

**Comment by markstory** [comment]
I pushed up a change so UpgradeShell uses the latest tagged app skeleton. You should be able to use `upgrade skeleton` to get the latest index.php file now.

**Comment by InheritX** [comment]
Hello @markstory 

I have upgraded cakephp using following link:
http://book.cakephp.org/3.0/en/upgrade-tool.html

But still I got the same error as above one. I have removed lib folder from root and now next error is showing me, so how to fix it ?

You have mention that that "I pushed up a change so UpgradeShell uses the latest tagged app skeleton. You should be able to use upgrade skeleton to get the latest index.php file now."

So from where I will get that update ?

**Comment by GitHubCorn** [comment]
I have just today on Thursday, January 5th, 2017, used the update tool to update my cakphp 2 app to cakephp 3 code, and I am still getting this same error: `Fatal error: Cannot declare class lib\Cake\Core\App because the name is already in use`, so this is not fixed yet. I really need this fixed, as I am now using a vps that has ubuntu 16 on it which only allows php 7, not php 5, which in turn doesn't allow me to use some of my encryption code, but the replacement encryption code requires me to update to cakphp 3 from cakephp 2, and when I try to do that, I get this error. Now I'm stuck and cannot work on my project till this is fixed. I really need this fixed.

I'm using the instructions from this page: https://github.com/cakephp/upgrade

**Comment by markstory** [comment]
> so this is not fixed yet.

Ok, how can someone else reproduce the issue you're seeing? I tried again tonight and was unable to. Until I can reproduce the problem it is 'fixed' from my point of view.

**Comment by GitHubCorn** [comment]
I think my problem has something to do with me also not having the latest version index.php in app/webroot, because I found the updated index.php and tried replacing it, but now I am getting a different error:

Fatal error: Uncaught Error: Class 'Cake\Http\Server' not found in /usr/share/nginx/html/web/app/webroot/index.php:33 Stack trace: #0 /usr/share/nginx/html/web/index.php(47): require() #1 {main} thrown in /usr/share/nginx/html/web/app/webroot/index.php on line 33

So I checked `/usr/share/nginx/html/web/app/lib` and ran `ls`, I get:

basics.php  bootstrap.php  config  Configure  Controller  Error  I18n         Log    Network  src   tests      Utility      View
bin         Cache          Config  Console    Core        Event  LICENSE.txt  Model  Routing  Test  TestSuite  VERSION.txt

it seems, I am missing an `Http` folder, and that seems to be the cause of my problem. I am also seem to be missing many other folders, based on what I see on this page: `https://api.cakephp.org/3.3/`, those are:

`Auth`, `Collection`, `Database`, `Datasource`, `Filesystem`, `Form`, `Mailer`, `ORM`, `Shell`, `Utility`, and `Validation` 

Is there some way I can download/install these missing components of CakePHP, where can I find them?

**Comment by markstory** [comment]
> Is there some way I can download/install these missing components of CakePHP, where can I find them?

Yes they are on github. You can either download a [zip file](github.com/cakephp/cakephp/releases) or use composer to get the current version of 3.3.

**Comment by GitHubCorn** [comment]
Ok, I have tried taking the files, and putting them under the folder /usr/share/nginx/html/web/lib. (I was also missing Application.php, so I found that, and copied that to /usr/share/nginx/html/web/lib/App/Application.php (where most other files are under /usr/share/nginx/html/web/lib/Cake. But I still got the same error:

Fatal error: Uncaught Error: Class 'Cake\Http\Server' not found in /usr/share/nginx/html/web/app/webroot/index.php:33 Stack trace: #0 /usr/share/nginx/html/web/index.php(47): require() #1 {main} thrown in /usr/share/nginx/html/web/app/webroot/index.php on line 33

So now I have begun trying to modify the core cakephp code, which I don't think I'm supposed to have to do, but it seems to be fixing the error one at a time, moving to another error. All these errors seem to be about a class not existing. So I have been putting into /usr/share/nginx/html/web/index.php between this part:

if (!defined('CAKE_CORE_INCLUDE_PATH')) {
        define('CAKE_CORE_INCLUDE_PATH', ROOT . DS . 'lib');
}

and

require APP_DIR . DS . WEBROOT_DIR . DS . 'index.php';

I added these lines:

require_once CAKE_CORE_INCLUDE_PATH . DS . 'Cake' . DS . 'Cache' . DS . 'Cache.php';
require_once CAKE_CORE_INCLUDE_PATH . DS . 'Cake' . DS . 'Http' . DS . 'Runner.php';
require_once CAKE_CORE_INCLUDE_PATH . DS . 'Cake' . DS . 'Http' . DS . 'BaseApplication.php';
require_once CAKE_CORE_INCLUDE_PATH . DS . 'App' . DS . 'Application.php';
require_once CAKE_CORE_INCLUDE_PATH . DS . 'Cake' . DS . 'Event' . DS . 'EventDispatcherTrait.php';
require_once CAKE_CORE_INCLUDE_PATH . DS . 'Cake' . DS . 'Http' . DS . 'Server.php';

For the EventDispatcherTrait.php line I had to find that file separately, as it was not in the latest stable tar.gz file of the link you pointed me to for some reason, even though it seems to be needed for even a basic installation of CakePHP to work.

Also once I got to 
require_once CAKE_CORE_INCLUDE_PATH . DS . 'Cake' . DS . 'Cache' . DS . 'Cache.php';
I got this error:

Parse error: syntax error, unexpected '%', expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST) or \\ (T_NS_SEPARATOR) in /usr/share/nginx/html/web/lib/Cake/Cache/Cache.php on line 18

and when I check this line I found:

use %s as a base class.', 'CacheEngine'));

This seems to not make sense, and I tried commenting it out, but then I got this error:

Parse error: syntax error, unexpected '%', expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST) or \\ (T_NS_SEPARATOR) in /usr/share/nginx/html/web/lib/Cake/Cache/Cache.php on line 18

Parse error: syntax error, unexpected 'cake_dev' (T_STRING), expecting ',' or ')' in /usr/share/nginx/html/web/lib/Cake/Cache/Cache.php on line 187, so on the lines around line 187, I found this that was causing a problem:

                if (!is_subclass_of($cacheClass, 'CacheEngine')) {
                        throw new CacheException(__d('cake_dev', 'Cache engines must            }
                static::$_engines[$name] = new $cacheClass();
                if (!static::$_engines[$name]->init($config)) {
                        $msg = __d(
                                'cake_dev',
                                'Cache engine "%s" is not properly configured. Ensure required extensions are installed, and credentials/permissions are correct',
                                $name
                        );
                        throw new CacheException($msg);
                }

'cake_dev' is the line 187, where it says the error is, but it's actually a syntax error on this line:

                       throw new CacheException(__d('cake_dev', 'Cache engines must            }

I don't know why that is like that, and I don't know what the message is supposed to be after 'Cache engines must', but I changed

                     throw new CacheException(__d('cake_dev', 'Cache engines must            }

to 

                     throw new CacheException(__d('cake_dev', 'Cache engines must'));
              }

and after doing that I get this error:

Fatal error: Cannot declare class lib\Cake\Cache\Cache because the name is already in use in /usr/share/nginx/html/web/lib/Cake/Cache/Cache.php on line 49

line 49 says this: `class Cache {`

I tried fixing this by commenting out line 19 of the same file, which says this:

`use Cake\Cache\Cache;`

After doing that, I get this error:

Fatal error: Uncaught Error: Class 'Cache' not found in /usr/share/nginx/html/web/app/config/bootstrap.php:26 Stack trace: #0 /usr/share/nginx/html/web/lib/Cake/Http/BaseApplication.php(61): require_once() #1 /usr/share/nginx/html/web/lib/Cake/Http/Server.php(72): Cake\Http\BaseApplication->bootstrap() #2 /usr/share/nginx/html/web/app/webroot/index.php(37): Cake\Http\Server->run() #3 /usr/share/nginx/html/web/index.php(48): require('/usr/share/ngin...') #4 {main} thrown in /usr/share/nginx/html/web/app/config/bootstrap.php on line 26

**Comment by markstory** [comment]
There shouldn't be a lib directory anymore in a 3.x application. And you shouldn't have to edit the framework code. You should move/delete you lib directory and instead use composer to install cakephp and its dependencies.

**Comment by GitHubCorn** [comment]
I tried using composer to install cakephp 3, but I got a 404 error at the root at the application? Are there different ningx config requirements from cakephp 2 to cakephp 3 ? (As for the lib directory I copied those files over from the src directory to try to fix the 404 error), and started causing those other errors.

**Comment by markstory** [comment]
> Are there different ningx config requirements different from cakephp 2 to cakephp 3 

There are. The nginx configuration is in the documentation.

**Comment by WallisonCarlos** [comment]
Why he uses the use 

```
namespace lib\Cake\Core;

use Cake\Cache\Cache;
use Cake\Core\App;
use Cake\Core\Plugin;
use Cake\Utility\Inflector;
```
than

```
namespace Cake\Core;

use Cake\Cache\Cache;
//use Cake\Core\App;
use Cake\Core\Plugin;
use Cake\Utility\Inflector;
```

? Solved problem.
